Add option to not accept maps with duplicate keys
hildjj/node-cbor pull request #161
Opened 2021-11-02 20:10 UTC by KubqoA

This PR adds a Decoder option to prevent the decoder from parsing maps with duplicate keys, which is one of the valid ways to handle duplicate map keys as described in the CBOR RFC.

Citing from CBOR RFC 8949:
[3.1 Major types, Major type 5](https://www.rfc-editor.org/rfc/rfc8949.html#name-major-types)
> A map that has duplicate keys may be well-formed, but it is not valid, and thus it causes indeterminate decoding; see also Section 5.6.

[5.6. Specifying Keys for Maps](https://www.rfc-editor.org/rfc/rfc8949.html#map-keys)
> When processing maps that exhibit entries with duplicate keys, a generic decoder might do one of the following:
> * Not accept maps with duplicate keys ...
> * Pass all map entries to the application ...
> * Lose some entries with duplicate keys, e.g., deliver only the final (or first) entry out of the entries with the same key ...
> Generic decoders need to document which of these three approaches they implement.

I believe this package chose the third option, although not documented, but in my use of CBOR I found it quite useful to have an option to not accept maps with duplicate keys. I decided to implement it via a Decoder option as to not break backwards compatibility.

2021-11-02 22:23 UTC, hildjj commented
I agree this is interesting.  I'll get to doing a full review in a day or two.  In the meantime, can you add yourself to the contributors in the `packages/cbor/package.json` file, please?

https://github.com/hildjj/node-cbor/blob/815ba89b6e4f5431cf4db4dffb73431bf1b6cd8e/packages/cbor/package.json#L39

2021-11-03 07:28 UTC, KubqoA commented
Thanks! Added myself to the contributors and also added a few more tests.

2021-11-08 13:21 UTC, KubqoA commented
Hi, sorry to bother you, just wanted to ask if you had any time to look at the changes? Thanks :)

2021-11-08 15:54 UTC, hildjj requested changes
Minor nits.  Otherwise great patch!
Will merge after nit fix.

2021-11-08 15:54 UTC, hildjj commented on packages/cbor/lib/decoder.js
> + * @property {boolean} [allowMapsWithDuplicateKeys=true] If false, error is
I think this would be better as `preventDuplicateKeys` so that the default can be false.

2021-11-08 15:54 UTC, hildjj commented on packages/cbor/lib/decoder.js
> +                    throw Error('Duplicate keys in a map')
please add `new` before `Error`.

2021-11-08 15:54 UTC, hildjj commented on packages/cbor/lib/decoder.js
> +                    throw Error('Duplicate keys in a map')
Add `new`

2021-11-08 15:54 UTC, hildjj commented on packages/cbor/test/decoder.ava.js
> +  // default behaviour is unchaned and allows parsing maps with duplicate keys
"unchanged"

2021-11-08 20:34 UTC, KubqoA commented
Made the changes, also found some `eslint` errors in my code, so fixed those as well. Hope everything is good now :)

2021-11-08 20:35 UTC, merged